### ISSUE TITLE
Cooked solution links broken

### ISSUE THREAD

**Issue by tomjw64** [Connexions/cnx-publishing#133]
Context is missing on generated intra-book links, for example, the links in the glossary index in Introductory Statistics on CTE Dev.

Links in the Answer Key section of Principles of Economics in CTE Dev are linking back to a section rather than the exercise with the id in the link address.

For example: Solution 1 of Chapter 1 in the answer key has the address http://cte-cnx-dev.cnx.org/contents/69619d2b-68f0-44b0-b074-a9b2bf90b2c6@11.326:1#fs-idm91372672
but links to the preface despite that the element of id fs-idm91372672 appears in Chapter 1 Self-Check Questions.

**Comment by karenc** [comment]
To provide extra information for this ticket, the answer key is here: http://cte-cnx-dev.cnx.org/contents/aWGdK2jw@11.326:RPeQk8jq@1/Answer-Key

**Comment by karenc** [comment]
From what I see, context is not missing on generated intra-book links in the glossary index in Introductory Statistics:

http://cte-cnx-dev.cnx.org/contents/MBiUQmmY@17.55:r9gqD6J7@1/Index

Am I missing something?

**Comment by karenc** [comment]
It seems we're linking to the original page "What is Economics, and Why is it Important?" (http://cte-cnx-dev.cnx.org/contents/6RH0nLs4@8/What-Is-Economics-and-Why-Is-I) that has the self check question "What is scarcity?", instead of the new composite page http://cte-cnx-dev.cnx.org/contents/aWGdK2jw@11.326:5Mnz_12i@1/Self-Check-Questions.

**Comment by karenc** [comment]
Closed via https://github.com/Connexions/cnx-epub/pull/89
