### ISSUE TITLE
Cannot publish derived copy on beta or dev

### ISSUE THREAD

**Issue by amberwebb** [Connexions/cnx-publishing#91]
I derived Understanding Basic Music Theory. I derived Staff module. Tried to publish but got 400 bad request error. 628d8305-c924-4b18-8ba8-e21da4111b8c

**Comment by pumazi** [comment]
Implementing Connexions/cnx-publishing#85 would help debug this.

Also, I believe issue is in cnx-authoring's use of cnx-epub, rather than publishing related. But that's only a guess at the moment.

**Comment by amberwebb** [comment]
@pumazi If the issue is in authoring then wouldn't the authoring pyramid.log file show an error? It's not.

**Comment by pumazi** [comment]
@amberwebb At first glance, yes. cnx-publishing is indeed raising the exception. The issue is related to [a cnx-epub change](https://github.com/Connexions/cnx-epub/pull/40). The change was an attempt to correct a rather sporadic exception that happened on publish. However, I'm fairly certain the issue is in the creation of the epub (in cnx-authoring via cnx-epub) rather than the consumption (in cnx-publishing via cnx-epub). That's why I'm suggesting the issue lies within cnx-authoring.

**Comment by edwoodward** [comment]
I was able to publish a derived Page on dev this morning.  @amberwebb should retest this.

**Comment by amberwebb** [comment]
This is now working on dev.
